// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    [Migration("20260910145616_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("DeviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceLogId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceLogId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IsAvailable = true,
                            Name = "Com ga",
                            Price = 35000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 2,
                            IsAvailable = true,
                            Name = "Com suon",
                            Price = 35000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 3,
                            IsAvailable = true,
                            Name = "Com tam",
                            Price = 30000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 4,
                            IsAvailable = true,
                            Name = "Bun bo",
                            Price = 40000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 5,
                            IsAvailable = true,
                            Name = "Pho bo",
                            Price = 45000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 6,
                            IsAvailable = true,
                            Name = "Mi quang",
                            Price = 35000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 7,
                            IsAvailable = true,
                            Name = "Banh mi thit",
                            Price = 20000m,
                            Unit = "o"
                        },
                        new
                        {
                            MenuItemId = 8,
                            IsAvailable = true,
                            Name = "Xoi ga",
                            Price = 25000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 9,
                            IsAvailable = true,
                            Name = "Che dau xanh",
                            Price = 15000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 10,
                            IsAvailable = true,
                            Name = "Tra sua tran chau",
                            Price = 30000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 11,
                            IsAvailable = true,
                            Name = "Nuoc cam ep",
                            Price = 20000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 12,
                            IsAvailable = true,
                            Name = "Sinh to bo",
                            Price = 25000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 13,
                            IsAvailable = true,
                            Name = "Banh bao nhan thit",
                            Price = 15000m,
                            Unit = "cai"
                        },
                        new
                        {
                            MenuItemId = 14,
                            IsAvailable = true,
                            Name = "Hu tieu nam vang",
                            Price = 40000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 15,
                            IsAvailable = true,
                            Name = "Chao ga",
                            Price = 30000m,
                            Unit = "to"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("OrderTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderTicketId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderTicketId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("TicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketLineId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketLineId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });
#pragma warning restore 612, 618
        }
    }
}
