// <auto-generated />
using System;
using FCanteen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCanteen.Data.Migrations
{
    [DbContext(typeof(FCanteenContext))]
    [Migration("20260923133050_AddLab04MvcSchema")]
    partial class AddLab04MvcSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCanteen.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "CÆ¡m, bÃºn, phá»Ÿ, mÃ¬ cÃ¡c loáº¡i",
                            Name = "MÃ³n chÃ­nh"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "BÃ¡nh mÃ¬, xÃ´i, bÃ¡nh bao Äƒn nháº¹",
                            Name = "MÃ³n phá»¥"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "TrÃ  sá»¯a, nÆ°á»›c Ã©p, sinh tá»‘",
                            Name = "Äá»“ uá»‘ng"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "ChÃ¨, sá»¯a chua, hoa quáº£",
                            Name = "TrÃ¡ng miá»‡ng"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DailySettlement", b =>
                {
                    b.Property<int>("DailySettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailySettlementId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CalculationTimeMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.HasKey("DailySettlementId");

                    b.ToTable("DailySettlements");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DeviceLog", b =>
                {
                    b.Property<int>("DeviceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceLogId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceLogId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.DiscountPolicyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiscountPolicyLogs");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningThreshold")
                        .HasColumnType("int");

                    b.HasKey("IngredientId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            CostPrice = 18000m,
                            Name = "Gao Thom",
                            StockQuantity = 500,
                            SupplierId = 1,
                            Unit = "kg",
                            WarningThreshold = 50
                        },
                        new
                        {
                            IngredientId = 2,
                            CostPrice = 65000m,
                            Name = "Thit Ga",
                            StockQuantity = 200,
                            SupplierId = 1,
                            Unit = "kg",
                            WarningThreshold = 30
                        },
                        new
                        {
                            IngredientId = 3,
                            CostPrice = 90000m,
                            Name = "Suon Heo",
                            StockQuantity = 150,
                            SupplierId = 1,
                            Unit = "kg",
                            WarningThreshold = 25
                        },
                        new
                        {
                            IngredientId = 4,
                            CostPrice = 180000m,
                            Name = "Thit Bo",
                            StockQuantity = 100,
                            SupplierId = 1,
                            Unit = "kg",
                            WarningThreshold = 20
                        },
                        new
                        {
                            IngredientId = 5,
                            CostPrice = 22000m,
                            Name = "Duong Cat",
                            StockQuantity = 300,
                            SupplierId = 2,
                            Unit = "kg",
                            WarningThreshold = 40
                        },
                        new
                        {
                            IngredientId = 6,
                            CostPrice = 24000m,
                            Name = "Sua Dac",
                            StockQuantity = 400,
                            SupplierId = 2,
                            Unit = "lon",
                            WarningThreshold = 50
                        },
                        new
                        {
                            IngredientId = 7,
                            CostPrice = 20000m,
                            Name = "Banh Pho",
                            StockQuantity = 80,
                            SupplierId = 1,
                            Unit = "kg",
                            WarningThreshold = 15
                        },
                        new
                        {
                            IngredientId = 8,
                            CostPrice = 120000m,
                            Name = "Tra Den",
                            StockQuantity = 50,
                            SupplierId = 2,
                            Unit = "kg",
                            WarningThreshold = 10
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0001",
                            Name = "Com ga",
                            Price = 35000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 2,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0002",
                            Name = "Com suon",
                            Price = 35000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 3,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0003",
                            Name = "Com tam",
                            Price = 30000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 4,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0004",
                            Name = "Bun bo",
                            Price = 40000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 5,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0005",
                            Name = "Pho bo",
                            Price = 45000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 6,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0006",
                            Name = "Mi quang",
                            Price = 35000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 7,
                            CategoryId = 2,
                            IsAvailable = true,
                            ItemCode = "MON-0007",
                            Name = "Banh mi thit",
                            Price = 20000m,
                            Unit = "o"
                        },
                        new
                        {
                            MenuItemId = 8,
                            CategoryId = 2,
                            IsAvailable = true,
                            ItemCode = "MON-0008",
                            Name = "Xoi ga",
                            Price = 25000m,
                            Unit = "phan"
                        },
                        new
                        {
                            MenuItemId = 9,
                            CategoryId = 4,
                            IsAvailable = true,
                            ItemCode = "MON-0009",
                            Name = "Che dau xanh",
                            Price = 15000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 10,
                            CategoryId = 3,
                            IsAvailable = true,
                            ItemCode = "MON-0010",
                            Name = "Tra sua tran chau",
                            Price = 30000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 11,
                            CategoryId = 3,
                            IsAvailable = true,
                            ItemCode = "MON-0011",
                            Name = "Nuoc cam ep",
                            Price = 20000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 12,
                            CategoryId = 3,
                            IsAvailable = true,
                            ItemCode = "MON-0012",
                            Name = "Sinh to bo",
                            Price = 25000m,
                            Unit = "ly"
                        },
                        new
                        {
                            MenuItemId = 13,
                            CategoryId = 2,
                            IsAvailable = true,
                            ItemCode = "MON-0013",
                            Name = "Banh bao nhan thit",
                            Price = 15000m,
                            Unit = "cai"
                        },
                        new
                        {
                            MenuItemId = 14,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0014",
                            Name = "Hu tieu nam vang",
                            Price = 40000m,
                            Unit = "to"
                        },
                        new
                        {
                            MenuItemId = 15,
                            CategoryId = 1,
                            IsAvailable = true,
                            ItemCode = "MON-0015",
                            Name = "Chao ga",
                            Price = 30000m,
                            Unit = "to"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItemIngredient", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MenuItemId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MenuItemIngredients");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 1,
                            Quantity = 0.15m
                        },
                        new
                        {
                            MenuItemId = 1,
                            IngredientId = 2,
                            Quantity = 0.20m
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 1,
                            Quantity = 0.15m
                        },
                        new
                        {
                            MenuItemId = 2,
                            IngredientId = 3,
                            Quantity = 0.18m
                        },
                        new
                        {
                            MenuItemId = 4,
                            IngredientId = 4,
                            Quantity = 0.10m
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 7,
                            Quantity = 0.25m
                        },
                        new
                        {
                            MenuItemId = 5,
                            IngredientId = 4,
                            Quantity = 0.12m
                        },
                        new
                        {
                            MenuItemId = 10,
                            IngredientId = 8,
                            Quantity = 0.03m
                        },
                        new
                        {
                            MenuItemId = 10,
                            IngredientId = 6,
                            Quantity = 0.10m
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Property<int>("OrderTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderTicketId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderTicketId");

                    b.ToTable("OrderTickets");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<int>("PurchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderLineId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseOrderLineId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            BranchCode = "CS1",
                            FullName = "Nguyen Van An",
                            Role = "Cashier",
                            StaffCode = "NV01"
                        },
                        new
                        {
                            StaffId = 2,
                            BranchCode = "CS1",
                            FullName = "Tran Thi Binh",
                            Role = "Manager",
                            StaffCode = "NV02"
                        },
                        new
                        {
                            StaffId = 3,
                            BranchCode = "CS2",
                            FullName = "Le Van Cuong",
                            Role = "Chef",
                            StaffCode = "NV03"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Ngu Hanh Son, Da Nang",
                            Email = "thucpham@fpt.vn",
                            Name = "NPP Thuc Pham Sach FPT",
                            Phone = "0905123456"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Hai Chau, Da Nang",
                            Email = "douong@fpt.vn",
                            Name = "NPP Do Uong & Nhat Giai Khat",
                            Phone = "0905987654"
                        });
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.Property<int>("TicketLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketLineId"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderTicketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketLineId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderTicketId");

                    b.ToTable("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Ingredient", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Supplier", "Supplier")
                        .WithMany("Ingredients")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItemIngredient", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("MenuItemIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("MenuItemIngredients")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.TicketLine", b =>
                {
                    b.HasOne("FCanteen.Data.Entities.MenuItem", "MenuItem")
                        .WithMany("TicketLines")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FCanteen.Data.Entities.OrderTicket", "OrderTicket")
                        .WithMany("TicketLines")
                        .HasForeignKey("OrderTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("MenuItemIngredients");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.MenuItem", b =>
                {
                    b.Navigation("MenuItemIngredients");

                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.OrderTicket", b =>
                {
                    b.Navigation("TicketLines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FCanteen.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
